spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://117.50.174.154:5432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080